export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS"
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR"

export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS"
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR"
