export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS"
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR"

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_ERROR = "USER_AUTH_ERROR"

export const UPLOAD_POST_SUCCESS ="UPLOAD_POST_SUCCESS"
export const UPLOAD_POST_ERROR ="UPLOAD_POST_ERROR"

export const ADD_LIKES = "ADD_LIKES"
export const REMOVE_LIKE = "REMOVE_LIKE"